# CNN MODEL FOR AMERICAN SIGN LANGUAGE

the dataset is taken from kaggle .
It contains total of 87000 images and i had removed some images from training set and added to testing set.
the dataset contains 86972 training images and 55 testing images  of 200x200 of size , with their lables .

1. `x_train`: Images used for training the neural network
2. `y_train`: Correct labels for the `x_train` images, used to evaluate the model's predictions during training
3. `x_test`: Images set aside for validating the performance of the model after it has been trained
4. `y_test`: Correct labels for the `x_test` images, used to evaluate the model's predictions after it has been trained

In [1]:
#loading test dataset
from PIL import Image
from glob import glob
import numpy as np
import pickle
import cv2
import os

test_dataset_path = './asl/asl_alphabet_test'

# Initialize empty lists to store x_test and y_test
x_test = []
y_test = []
target_size = (64, 64)

# Iterate through each image in the test directory
for image_name in os.listdir(test_dataset_path):
    image_path = os.path.join(test_dataset_path, image_name)

    # Open the image using PIL
    img = Image.open(image_path)
    
    #resizing the image
    img = img.resize(target_size)

    # Convert the image to a numpy array and append to x_test
    x_test.append(np.array(img))

   
    label = image_name.split('.')[0]
    y_test.append(label)

# Convert lists to numpy arrays for further processing
x_test = np.array(x_test)
y_test = np.array(y_test)

# Print the shapes of x_test and y_test
print("x_test shape:", x_test.shape)
print("y_test shape:", y_test.shape)


x_test shape: (55, 64, 64, 3)
y_test shape: (55,)


In [2]:
import os
from PIL import Image
import numpy as np

dataset_path = './asl/asl_alphabet_train'

# Initialize empty lists to store x_train and y_train
x_train = []
y_train = []

# Resize target size
target_size = (64, 64)  # Adjust the target size as needed

# Iterate through each subfolder in the train directory
for class_name in os.listdir(dataset_path):
    class_path = os.path.join(dataset_path, class_name)

    # Check if the path is a directory
    if os.path.isdir(class_path):
        # Iterate through each image in the subfolder
        for image_name in os.listdir(class_path):
            image_path = os.path.join(class_path, image_name)

            # Open the image using PIL
            img = Image.open(image_path)


            # Resize the image
            img = img.resize(target_size)

            # Convert the image to a numpy array and append to x_train
            x_train.append(np.array(img))

            # Append the label (class name) to y_train
            y_train.append(class_name)

# Convert lists to numpy arrays for further processing
x_train = np.array(x_train)
y_train = np.array(y_train)

# Print the shapes of x_train and y_train
print("x_train shape:", x_train.shape)
print("y_train shape:", y_train.shape)


x_train shape: (86972, 64, 64, 3)
y_train shape: (86972,)


# Exploring the ASL Data

In [3]:
x_train[0]

array([[[ 12,   7, 216],
        [ 22,  21, 163],
        [ 22,  19, 163],
        ...,
        [ 79,  71, 213],
        [ 82,  73, 215],
        [ 59,  52, 223]],

       [[ 25,  18, 166],
        [ 59,  50,  38],
        [ 64,  48,  33],
        ...,
        [200, 183, 169],
        [208, 188, 172],
        [148, 133, 187]],

       [[ 26,  23, 167],
        [ 71,  55,  41],
        [ 72,  52,  36],
        ...,
        [199, 180, 161],
        [203, 183, 162],
        [145, 131, 184]],

       ...,

       [[ 52,  55, 203],
        [138, 143, 141],
        [134, 141, 134],
        ...,
        [145, 138, 134],
        [148, 141, 131],
        [108,  99, 163]],

       [[ 55,  56, 201],
        [140, 145, 143],
        [137, 144, 136],
        ...,
        [149, 139, 133],
        [152, 142, 128],
        [111,  99, 161]],

       [[ 41,  39, 216],
        [102, 104, 167],
        [ 99, 105, 164],
        ...,
        [105, 101, 166],
        [106, 102, 163],
        [ 77,  71, 187]]

In [4]:
x_test[0]

array([[[ 11,   8, 215],
        [ 23,  19, 165],
        [ 25,  18, 161],
        ...,
        [ 80,  72, 215],
        [ 82,  74, 213],
        [ 58,  52, 223]],

       [[ 23,  21, 163],
        [ 62,  50,  37],
        [ 63,  46,  32],
        ...,
        [200, 184, 167],
        [206, 187, 169],
        [148, 133, 184]],

       [[ 30,  22, 167],
        [ 71,  56,  40],
        [ 65,  54,  37],
        ...,
        [198, 180, 161],
        [202, 182, 161],
        [145, 131, 185]],

       ...,

       [[ 54,  55, 202],
        [141, 141, 141],
        [139, 140, 134],
        ...,
        [150, 140, 137],
        [150, 139, 130],
        [109,  98, 165]],

       [[ 53,  57, 202],
        [141, 146, 143],
        [138, 143, 136],
        ...,
        [149, 141, 133],
        [150, 143, 127],
        [110, 100, 163]],

       [[ 38,  41, 219],
        [102, 106, 168],
        [ 99, 103, 166],
        ...,
        [107,  99, 166],
        [109, 101, 164],
        [ 80,  72, 183]]

In [5]:
y_train

array(['A', 'A', 'A', ..., 'Z', 'Z', 'Z'], dtype='<U7')

In [6]:
y_test

array(['A', 'A', 'A', 'A', 'B', 'C', 'C', 'C', 'C', 'D', 'D', 'D', 'D',
       'D', 'D', 'D', 'del', 'del', 'del', 'E', 'E', 'E', 'E', 'F', 'F',
       'F', 'F', 'G', 'G', 'G', 'G', 'H', 'I', 'J', 'K', 'L', 'M', 'N',
       'nothing', 'O', 'P', 'Q', 'Q', 'Q', 'Q', 'Q', 'S', 'space', 'T',
       'U', 'V', 'W', 'X', 'Y', 'Z'], dtype='<U7')

In [7]:
x_test.max()

255

In [8]:
x_test.min()

3

In [9]:
x_train.min()

0

In [10]:
x_train.max()

255

# Preparing the Data for Training

1.Normalize the image data, to make the image input values easier to work with for the model

2.Categorize the labels, to make the label values easier to work with for the model

In [11]:
#normalizing the data
x_train = x_train / 255.0  # Scaling to the range [0, 1]
x_test = x_test / 255.0  # Scaling to the range [0, 1]


In [12]:
#reshape
x_train = x_train.reshape(-1,64,64,3)
x_test = x_test.reshape(-1,64,64,3)

In [13]:
x_train[0]

array([[[0.04705882, 0.02745098, 0.84705882],
        [0.08627451, 0.08235294, 0.63921569],
        [0.08627451, 0.0745098 , 0.63921569],
        ...,
        [0.30980392, 0.27843137, 0.83529412],
        [0.32156863, 0.28627451, 0.84313725],
        [0.23137255, 0.20392157, 0.8745098 ]],

       [[0.09803922, 0.07058824, 0.65098039],
        [0.23137255, 0.19607843, 0.14901961],
        [0.25098039, 0.18823529, 0.12941176],
        ...,
        [0.78431373, 0.71764706, 0.6627451 ],
        [0.81568627, 0.7372549 , 0.6745098 ],
        [0.58039216, 0.52156863, 0.73333333]],

       [[0.10196078, 0.09019608, 0.65490196],
        [0.27843137, 0.21568627, 0.16078431],
        [0.28235294, 0.20392157, 0.14117647],
        ...,
        [0.78039216, 0.70588235, 0.63137255],
        [0.79607843, 0.71764706, 0.63529412],
        [0.56862745, 0.51372549, 0.72156863]],

       ...,

       [[0.20392157, 0.21568627, 0.79607843],
        [0.54117647, 0.56078431, 0.55294118],
        [0.5254902 , 0

In [14]:
x_test[0]

array([[[0.04313725, 0.03137255, 0.84313725],
        [0.09019608, 0.0745098 , 0.64705882],
        [0.09803922, 0.07058824, 0.63137255],
        ...,
        [0.31372549, 0.28235294, 0.84313725],
        [0.32156863, 0.29019608, 0.83529412],
        [0.22745098, 0.20392157, 0.8745098 ]],

       [[0.09019608, 0.08235294, 0.63921569],
        [0.24313725, 0.19607843, 0.14509804],
        [0.24705882, 0.18039216, 0.1254902 ],
        ...,
        [0.78431373, 0.72156863, 0.65490196],
        [0.80784314, 0.73333333, 0.6627451 ],
        [0.58039216, 0.52156863, 0.72156863]],

       [[0.11764706, 0.08627451, 0.65490196],
        [0.27843137, 0.21960784, 0.15686275],
        [0.25490196, 0.21176471, 0.14509804],
        ...,
        [0.77647059, 0.70588235, 0.63137255],
        [0.79215686, 0.71372549, 0.63137255],
        [0.56862745, 0.51372549, 0.7254902 ]],

       ...,

       [[0.21176471, 0.21568627, 0.79215686],
        [0.55294118, 0.55294118, 0.55294118],
        [0.54509804, 0

In [15]:
#defining the labels

labels_dict ={
    "A": 0,
    "B": 1,
    "C": 2,
    "D": 3,
    "del": 4,
    "E": 5,
    "F": 6,
    "G": 7,
    "H": 8,
    "I": 9,
    "J": 10,
    "K": 11,
    "L": 12,
    "M": 13,
    "N": 14,
    "nothing": 15,
    "O": 16,
    "P": 17,
    "Q": 18,
    "R": 19,
    "S": 20,
    "space": 21,
    "T": 22,
    "U": 23,
    "V": 24,
    "W": 25,
    "X": 26,
    "Y": 27,
    "Z": 28,
}

def encode_labels(y, labels_dict):

    return np.array([labels_dict[label] for label in y])

# Encode both y_train and y_test
y_train_encoded = encode_labels(y_train, labels_dict)
y_test_encoded = encode_labels(y_test, labels_dict)

# y_train_encoded and y_test_encoded are now arrays of numerical labels
print(y_train_encoded)
print(y_test_encoded)


[ 0  0  0 ... 28 28 28]
[ 0  0  0  0  1  2  2  2  2  3  3  3  3  3  3  3  4  4  4  5  5  5  5  6
  6  6  6  7  7  7  7  8  9 10 11 12 13 14 15 16 17 18 18 18 18 18 20 21
 22 23 24 25 26 27 28]


In [16]:
import tensorflow as tf

num_classes = len(labels_dict)  # Total number of classes

y_train_one_hot = tf.keras.utils.to_categorical(y_train_encoded, num_classes)
y_test_one_hot = tf.keras.utils.to_categorical(y_test_encoded, num_classes)


In [17]:
from tensorflow.keras.models import Sequential
from tensorflow.keras.layers import Conv2D, MaxPooling2D, Flatten, BatchNormalization, Dense, LeakyReLU

# Assuming input_shape and output_shape are defined elsewhere in your code
input_shape=(64,64,3)
model= Sequential()

# First Convolutional Layer
model.add(Conv2D(16, kernel_size=(3, 3), activation='relu', use_bias=True, input_shape=input_shape))
model.add(MaxPooling2D(pool_size=(2, 2)))
model.add(Conv2D(32, kernel_size=(3, 3),activation='relu',use_bias=True))
model.add(Conv2D(64,kernel_size=(3, 3),activation='relu', use_bias=True))
model.add(MaxPooling2D(pool_size=(2, 2)))
model.add(Flatten())
model.add(BatchNormalization())
model.add(Dense(128,activation='linear',use_bias=True))
model.add(LeakyReLU(alpha=0.01))
model.add(Dense(units=num_classes, activation='softmax', use_bias=True))


In [18]:
model.compile(optimizer='adam', loss='categorical_crossentropy', metrics=['accuracy'])

In [19]:
model.summary()

Model: "sequential"
_________________________________________________________________
 Layer (type)                Output Shape              Param #   
 conv2d (Conv2D)             (None, 62, 62, 16)        448       
                                                                 
 max_pooling2d (MaxPooling2  (None, 31, 31, 16)        0         
 D)                                                              
                                                                 
 conv2d_1 (Conv2D)           (None, 29, 29, 32)        4640      
                                                                 
 conv2d_2 (Conv2D)           (None, 27, 27, 64)        18496     
                                                                 
 max_pooling2d_1 (MaxPoolin  (None, 13, 13, 64)        0         
 g2D)                                                            
                                                                 
 flatten (Flatten)           (None, 10816)             0

In [20]:
history = model.fit(x_train , y_train_one_hot, validation_data=(x_test , y_test_one_hot), epochs=10, batch_size=32)


Epoch 1/10


2718/2718 [==============================] - 121s 43ms/step - loss: 0.4356 - accuracy: 0.8658 - val_loss: 0.4775 - val_accuracy: 0.9636
Epoch 2/10
2718/2718 [==============================] - 110s 41ms/step - loss: 0.0884 - accuracy: 0.9712 - val_loss: 0.7524 - val_accuracy: 0.9818
Epoch 3/10
2718/2718 [==============================] - 112s 41ms/step - loss: 0.0723 - accuracy: 0.9783 - val_loss: 1.1109 - val_accuracy: 0.9818
Epoch 4/10
2718/2718 [==============================] - 109s 40ms/step - loss: 0.0529 - accuracy: 0.9841 - val_loss: 1.6229 - val_accuracy: 0.9818
Epoch 5/10
2718/2718 [==============================] - 110s 40ms/step - loss: 0.0505 - accuracy: 0.9853 - val_loss: 1.7265 - val_accuracy: 0.9818
Epoch 6/10
2718/2718 [==============================] - 110s 40ms/step - loss: 0.0458 - accuracy: 0.9876 - val_loss: 1.4937 - val_accuracy: 0.9818
Epoch 7/10
2718/2718 [==============================] - 109s 40ms/step - loss: 0.0427 - accuracy: 0.9887 - val_loss:

In [21]:
model.save('my_model.h5')  


C:\Users\gnapika\AppData\Local\Programs\Python\Python310\lib\site-packages\keras\src\engine\training.py:3103: UserWarning: You are saving your model as an HDF5 file via `model.save()`. This file format is considered legacy. We recommend using instead the native Keras format, e.g. `model.save('my_model.keras')`.
  saving_api.save_model(


In [6]:
from tensorflow.keras.models import load_model
from tensorflow.keras.preprocessing import image
import numpy as np

# Load your trained model
model = load_model('my_model.h5')

# Load and preprocess the new image
img_path = './abc.jpeg'
img = image.load_img(img_path, target_size=(64, 64))  # Adjust target size as needed
img_array = image.img_to_array(img)
img_array = np.expand_dims(img_array, axis=0)
img_array /= 255.0  # Normalize pixel values to [0, 1]

# Make predictions
predictions = model.predict(img_array)

# Interpret the predictions
predicted_class_index = np.argmax(predictions)
predicted_label = [key for key, value in labels_dict.items() if value == predicted_class_index][0]
print("Predicted Label:", predicted_label)


1/1 [==============================] - 0s 85ms/step
Predicted Label: F


In [7]:
import cv2
import numpy as np
model = load_model('my_model.h5')

# Open the camera (camera index 0 by default)
cap = cv2.VideoCapture(0)

# Check if the camera opened successfully
if not cap.isOpened():
    print("Error: Could not open camera.")
    exit()

while True:
    # Capture frame-by-frame
    ret, frame = cap.read()

    # Check if the frame is empty
    if not ret:
        print("Error: Failed to capture frame.")
        break

    # Resize the frame to match the input size of your model
    img = cv2.resize(frame, (64, 64))

    # Normalize pixel values to [0, 1]
    img_array = img / 255.0  # Use the original resized frame

    # Expand dimensions to match the input shape expected by the model
    img_array = np.expand_dims(img_array, axis=0)

    # Make predictions
    predictions = model.predict(img_array)

    # Interpret the predictions
    predicted_class_index = np.argmax(predictions)
    predicted_label = [key for key, value in labels_dict.items() if value == predicted_class_index][0]

    # Display the frame with the predicted label
    cv2.putText(frame, f'Predicted Label: {predicted_label}', (10, 30), cv2.FONT_HERSHEY_SIMPLEX, 1, (0, 255, 0), 2)
    cv2.imshow('Sign Classification', frame)

    # Break the loop when 'q' is pressed
    if cv2.waitKey(1) & 0xFF == ord('q'):
        break

# Release the camera and close all windows
cap.release()
cv2.destroyAllWindows()


1/1 [==============================] - 0s 19ms/step


1/1 [==============================] - 0s 21ms/step


1/1 [==============================] - 0s 18ms/step
